from __future__ import annotations

from pathlib import Path
from typing import Any

from src.gui.erd.common import _erd_error, _require_project
from src.schema_project_io import load_project_from_json, save_project_to_json
from src.schema_project_model import SchemaProject


def export_schema_project_to_json(
    *,
    project: Any,
    output_path_value: Any,
) -> Path:
    current = _require_project(project)

    if not isinstance(output_path_value, str) or output_path_value.strip() == "":
        raise ValueError(
            _erd_error(
                "Schema export path",
                "output path is required",
                "choose a destination .json file path",
            )
        )

    output_path = Path(output_path_value.strip())
    if output_path.suffix.lower() != ".json":
        raise ValueError(
            _erd_error(
                "Schema export path",
                f"unsupported extension '{output_path.suffix or '<none>'}'",
                "use a .json output file extension",
            )
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        save_project_to_json(current, str(output_path))
    except ValueError as exc:
        raise ValueError(
            _erd_error(
                "Schema export",
                f"schema is invalid for export ({exc})",
                "fix schema validation issues and retry export",
            )
        ) from exc
    except OSError as exc:
        raise ValueError(
            _erd_error(
                "Schema export",
                f"failed to write schema JSON ({exc})",
                "check destination path permissions and retry",
            )
        ) from exc
    return output_path


def load_project_schema_for_erd(path_value: Any) -> SchemaProject:
    if not isinstance(path_value, str) or path_value.strip() == "":
        raise ValueError(
            _erd_error(
                "Schema path",
                "path is required",
                "choose an existing schema project JSON file",
            )
        )

    path = Path(path_value.strip())
    if not path.exists():
        raise ValueError(
            _erd_error(
                "Schema path",
                f"path '{path}' does not exist",
                "choose an existing schema project JSON file",
            )
        )

    try:
        return load_project_from_json(str(path))
    except Exception as exc:
        raise ValueError(
            _erd_error(
                "Schema input",
                f"failed to load schema JSON from '{path}' ({exc})",
                "provide a valid schema project JSON file generated by this application",
            )
        ) from exc
